### PR TITLE
Add function `represent_value`

### PR DESCRIPTION
**Pull request by m-kuhn**
This takes the widget configuration into consideration for values.
Makes it possible to use value maps, value relationes etc configuration of widgets
within expressions.

With QGIS 3, this will be on board.

image

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks @NathanW2 any timeline when this will be in a release / the plugin repository?

**Comment by NathanW2** [comment]
In about 5 minutes.

**Comment by NathanW2** [comment]
Should be there now.

**Comment by m-kuhn** [comment]
🎉 yay

**Pull request merged**
